package cmpe.cloudcomputing.robot.document;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.springframework.data.mongodb.core.mapping.Document;

//nosql mongodb use "Document" instead of 'Entity'
@Document
public class OrderRecord {
	
	@Id @GeneratedValue         // making this variable as ID, will be auto-generated by MongoDB
	private String id;

	private String order;
	private String location;
	private String ordertime;
	private String robotname;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getOrder() {
		return order;
	}
	public void setOrder(String order) {
		this.order = order;
	}
	public String getLocation() {
		return location;
	}
	public void setLocation(String location) {
		this.location = location;
	}
	public String getOrdertime() {
		return ordertime;
	}
	public void setOrdertime(String ordertime) {
		this.ordertime = ordertime;
	}
	public String getRobotname() {
		return robotname;
	}
	public void setRobotname(String robotname) {
		this.robotname = robotname;
	}
}
