package cmpe.cloudcomputing.robot.document;


import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.springframework.data.mongodb.core.mapping.Document;

//nosql mongodb use "Document" instead of 'Entity'
@Document
public class RobotRecord {
	
	@Id @GeneratedValue         // making this variable as ID, will be auto-generated by MongoDB
	private String id;

	private String name;
	private String status;
	
	public RobotRecord() {}
	
	public RobotRecord(String name, String status) {
		this.name = name;
		this.status = status;
	}

	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
}
